services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.3.0"
      MOTD: "wenapo"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "20"
      ONLINE_MODE: "false"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data